// Project info

name := "play-statsd"

// So that we can publish it into Sonatype

organization := "net.vz.play.statsd"

// The version comes from version.sbt, and is generated by the release plugin

scalaVersion := "2.10.0"

resolvers ++= Seq(
  "livingsocial" at "http://artifacts.livingsocial.net/artifactory/repo",
  Resolver.url("livingsocial-ivy", url("http://artifacts.livingsocial.net/artifactory/repo"))(Resolver.ivyStylePatterns)
)

// Dependencies

libraryDependencies ++= Seq(
    "play" %% "play" % "2.1-RC2"
)

// Test dependencies

libraryDependencies ++= Seq(
    "org.specs2" %% "specs2"     % "1.13" % "test",
    "play"       %% "play-test"  % "2.1-RC2" % "test"
)

parallelExecution in Test := false
